
PARTICLE_DEFAULT_SPAWN_NUM = 150


# ADVANCED CONTROLS
x = 1000

FRAME_RATE = 60
PARTICLE_LOSE_ENERGY = 1 - 0.9 * (1 / x)

PARTICLE_FORCE_LOWER_RANGE = 1
PARTICLE_FORCE_UPPER_RANGE = 100

WALL_HEAT = 2.5 * (1 / PARTICLE_LOSE_ENERGY)
WALL_BOUNDARY = 25

PARTICLE_DEFAULT_UPDATE_TIME = 1
PARTICLE_POWER_OF_DISTANCE = 1

# ALMOST NEVER CHANGES:
SCREEN_DIM = (x, x)

BACK_BLACK = (0, 0, 0)

PARTICLE_DEFAULT_RADIUS = 3

PARTICLE_COLOR_RED = (0xff, 0x00, 0x00)
PARTICLE_COLOR_YELLOW = (0xff, 0xA0, 0x00)
PARTICLE_COLOR_GREEN = (0x00, 0xff, 0x00)
PARTICLE_COLOR_BLUE = (0x00, 0x00, 0xff)
PARTICLE_COLOR_WHITE = (0xff, 0xff, 0xff)

# THE SPAWNING MARGINS
margin_x, margin_y = (0.25, 0.25)
center_x, center_y = (0.5, 0.5)
PARTICLE_DEFAULT_SPAWN_FRAME = (
    (
        int((center_x - margin_x) * (SCREEN_DIM[0] - 2 * WALL_BOUNDARY) + WALL_BOUNDARY),
        int((center_x + margin_x) * (SCREEN_DIM[0] - 2 * WALL_BOUNDARY) + WALL_BOUNDARY)
    ),
    (
        int((center_y - margin_y) * (SCREEN_DIM[1] - 2 * WALL_BOUNDARY) + WALL_BOUNDARY),
        int((center_y + margin_y) * (SCREEN_DIM[1] - 2 * WALL_BOUNDARY) + WALL_BOUNDARY)
    )
)
